### ISSUE TITLE
Issue if user forgets their username

### ISSUE THREAD

**Issue by DTri001** [NASA-Tournament-Lab/coeci-cms-mpsp#100]
If user forgets their username, there appears to be no way to get into the system.

**Comment by DTri001** [comment]
Secondary but related issue - if user enters their username correctly but enters a bad [ i.e. "undeliverable" ] email address, there is no way for the user to go back in and fix their email address as the system indicates the username already exists and won't let the user go any further.  In this case, the user will need to re-create their account with a new username.  We assume the former username associated with the undeliverable email address is now stuck in the system.

**Comment by DTri001** [comment]
Closed in error

**Comment by alamora** [comment]
Not a bug.  The user will have to create a new username.
