### ISSUE TITLE
Error 500 - Pharmacy Enrollment

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#102]
The following error occurred during new Pharmacy enrollment after entering facility credentials and moving to the next screen:

Error 500: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. There is not enough space on the disk.

**Comment by cyberjag** [comment]
This in environment specific. We have to expand the disk drive space in the VM as there is no space left.

**Comment by alamora** [comment]
Is this now resolved and working?

**Comment by cyberjag** [comment]
Since we upgraded the VM this should be working now.

**Comment by angied** [comment]
Nothing happens when you click Choose File on the Facility Credentials tab, and you can't advance if you don't upload a file. So I can't test this.
