### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#104]
Attempting to log in with an existing username and I get the attached error.
![capture](https://f.cloud.github.com/assets/4697941/1122814/46980894-1ae4-11e3-9cf7-b51d0d93c7f8.PNG)

When I tried to register a new username I get this error:
Error 500: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is javax.el.PropertyNotFoundException: Property 'enabled' not found on type java.lang.String

**Comment by alamora** [comment]
Which environment?

Andy LaMora
TopCoder, Inc
(p) 917-312-7406

**Comment by angied** [comment]
http://ec2-54-226-28-93.compute-1.amazonaws.com:9080/cms/login

**Comment by alamora** [comment]
Should be all set now

Andy LaMora
TopCoder, Inc
(p) 917-312-7406
