### ISSUE TITLE
Individual Member Info - Pharmacy

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#105]
Individual Member should not be required for Pharmacy provider type. 

Additionally, if they are adding affiliations, the only Individual Provider Type available for selection should be Pharmacist.

**Comment by angied** [comment]
Getting a server error after License Info tab; cannot get to the Individual Members tab to test.

**Comment by angied** [comment]
First part is fixed.

Individual Provider Type should default to Pharmacist, and does not need to be a drop down as they are only allowed to affiliate the one provider type.

**Comment by cyberjag** [comment]
This is fixed and ready for testing.

**Comment by angied** [comment]
Fixed.
