### ISSUE TITLE
Service Agent role missing Review

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#107]
The Review function is missing from Service Agent role. Under Enrollments and the Pending tab there are only COS, Edit, Print, and Export. Service Agents have no way of approving or denying applications.

**Comment by cyberjag** [comment]
What is the difference in permission settings between Service Admin and Service Agent? Currently Service Admin is having this review permission.

**Comment by cyberjag** [comment]
Added Review permission for Service Agent. Please note that this will be enabled only for new enrollments.

**Comment by angied** [comment]
It does show up for new enrollments, but we need it to show up for every Pending enrollment, regardless of the type.

Service Agents will be doing the bulk of all enrollment requests, so they need to have this function available.

**Comment by angied** [comment]
Service Admin will have the additional Functions tab, but the Service Agent role should be able to do everything else the Admin can do.

**Comment by cyberjag** [comment]
> > It does show up for new enrollments, but we need it to show up for every Pending enrollment, regardless of the type.

If enrollment already started in production we can do it. Otherwise its not really required and this is some considerable effort also.

**Comment by angied** [comment]
This is why I see under the Agent role login:
![image](https://f.cloud.github.com/assets/4697941/1706321/8fcdc9f0-60ed-11e3-84c5-0bf64c5273c8.png)

Review is an option for the first three in the list, but not for the rest. Will it be available on all submissions going forward whether they are new enrollments, re-enrollments, or record updates?

**Comment by cyberjag** [comment]
Yes, it will be available for all submissions going forward. Only the previous data is affected.
