### ISSUE TITLE
Server Error - MN environment

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#112]
This error happens when you try to create a new enrollment, for every provider type.

![image](https://f.cloud.github.com/assets/4697941/1262798/ffd41b8e-2c43-11e3-9834-3290fa0b042e.png)

**Comment by cyberjag** [comment]
Can you please try again?

http://ec2-54-226-28-93.compute-1.amazonaws.com:9080/cms/ops/viewDashboard

**Comment by angied** [comment]
It works in the amazon environment, just not the Minnesota one.
