### ISSUE TITLE
Username is required error

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#13]
The error "Username is required" comes up when attempting to log into the mn-its-test link. The username and password used are what I registered for, and what was returned in the confirmation email. Domain is MN-ITS.

**Comment by alamora** [comment]
This was due to the LDAP security model. 

The system design has been changed to use MN-ITS security instead.  This change is in progress.

Closing this ticket since it refers to the retired system.  When the new security model is deployed we will inform DHS.
