### ISSUE TITLE
Access Issues

### ISSUE THREAD

**Issue by gildewinberg** [NASA-Tournament-Lab/coeci-cms-mpsp#14]
1- Tried to register as a new user @ https://mn-its-test.dhs.state.mn.us/cms/login
2- Received 404 error/page cannot be found
3- Received email confirmation stating I have successfully registered 
4- When I use the User Name & Password I am not able to login, Please NOTE: The User Name does not match our current LDAP naming conventions.

**Comment by gildewinberg** [comment]
Emailed examples to Andy 06/26

**Comment by alamora** [comment]
The system was not active.  Closing ticket.
