### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by gildewinberg** [NASA-Tournament-Lab/coeci-cms-mpsp#16]
The users are currently authenticating directly against the LDAP, which we don’t do – this is why the app failed when pointed to Dev – 
Users should either authenticate through the WebGate/Access server (MN-ITS), or auth via SOAP request through WebPass/Identity Server (SMI)

**Comment by gildewinberg** [comment]
Some detail from Doug J:
1.  The application is set to use certificate authentication against the LDAP, which is not DHS policy – this is why the app failed when pointed to Dev
2.  The DIT structure was not designed to fit in with our model.  This requires an application code change to point the LDAP SearchBase to the MPSE directory structure as built to fit in with the current DIT.  This should be an easy fix, and I can provide the structural details.
3.  The RBAC in the application was designed to use groups, rather than user attributes – we can’t have 250,000+ users in a group due to SunOne Directory performance limitations, as well as administrative management of group memberships.
4.  The application is designed to authenticate users directly against the LDAP – they should either authenticate through the WebGate/Access server (MN-ITS), or auth via SOAP request through WebPass/Identity Server (SMI).  This is DHS policy for application authentication as part of our best practices.  Authentication services are provided through the Identity Management infrastructure, not through direct LDAP authentication.

**Comment by alamora** [comment]
This issue is being resolved by routing access through MN-ITS instead of LDAP, for state employees.  The system will look for appropriate tokens embedded with the access request from MN-ITS and allow the user that level of access.
