### ISSUE TITLE
FEIN is not required for Individual Provider in private practice

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#22]
Currently the FEIN is required for individual provider types who are in private practice. They can provide one, but it should not be required.

**Comment by cyberjag** [comment]
So FEIN is optional for both <b>Yes / No </b> answer to the question <i> Do you maintain your own private practice? </i>

**Comment by angied** [comment]
Correct.

**Comment by angied** [comment]
Fixed.
