### ISSUE TITLE
Private practice and group practice yes/no

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#30]
On the Practice Info tab, a provider cannot answer No to both questions:

Do you maintain your own private practice? 
Are you employed and/or independently contracted by a group practice?

If provider answers No to private practice, yes must be selected for the next question. 
If provider answers No to group practice, yes must be selected for the previous question.

**Comment by angied** [comment]
Still allows for No to both questions.

**Comment by cyberjag** [comment]
![screen shot 2013-12-20 at 10 49 51 am](https://f.cloud.github.com/assets/4492389/1788651/65f68e40-6936-11e3-89d1-a308b01eaab2.png)

I am not able to select No to both questions. This is enforced in business rules.

**Comment by angied** [comment]
Fixed.
