### ISSUE TITLE
Edit Provider Type to add required additional documentation- Service Admin

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#34]
Agreements, Addendums, and Assurance Statements are different for every provider type, so Service Admin needs to be able to associate the correct ones per type. Some may have 1, others may have several. There should be no limit. 

2.18 of CMS Medicaid Provider Screening Portal - Adminstrative Features ARS document.

**Comment by angied** [comment]
This is fixed, but can we get 100 characters in the Agreement Title field (under Add Agreement). It currently is maxed at 45, but we will need more.

**Comment by cyberjag** [comment]
Limit is set to 100 chars now. Please clear browser cache before testing this.

**Comment by angied** [comment]
Fixed.
