### ISSUE TITLE
Manage Agreements and Addendums - Service Admin

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#35]
Allow HTML or Rich Text format when creating/editing Agreements and Addendums.

I was unable to find this in 2.21 of CMS Medicaid Provider Screening Portal - Adminstrative Features ARS but it was part of feedback submitted 5-2013.

**Comment by angied** [comment]
The WYSIWYG editor works correctly, but when the agreement is saved it looks like this:
![image](https://f.cloud.github.com/assets/4697941/1777301/963a94ca-6823-11e3-8460-2c480e246db8.png)

When you get to the Provider Statement tab and see the list of Agreements, clicking the link just gives an error:
Error 404: SRVE0295E: Error reported: 404

Also, would like to indicate required or optional when assigning an agreement to a provider type.

**Comment by cyberjag** [comment]
> > Also, would like to indicate required or optional when assigning an agreement to a provider type.
> > Please create a new ticket for this requirement. Some amount of work is required for this.

Other issues are fixed.

**Comment by angied** [comment]
Fixed.
