### ISSUE TITLE
Ownership Info - Organization Enrollment

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#44]
When passing to the next screen after completing the Ownership Info tab, the name of the Individual person is mixed up. The First Name field becomes blank, and the data entered in that field moves to the Last Name field. The data entered in Last Name moves to Middle Name. 

Once corrected it passes.

**Comment by cyberjag** [comment]
Please make sure to clear browser cache before testing this.

**Comment by angied** [comment]
Fixed.
