### ISSUE TITLE
Issuing Board not allowed error - Physicians

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#47]
Error when passing to the next screen after completing license and specialty information on Physician new enrollment:

Issuing Board specified is not allowed for this provider type.(Specialty #1)

Once corrected, can move to next screen.

**Comment by cyberjag** [comment]
Fixed

**Comment by angied** [comment]
Getting a server error after clicking Next from License Info tab.

![image](https://f.cloud.github.com/assets/4697941/1658130/33121734-5b8e-11e3-8d6c-127b0c166b85.png)

**Comment by cyberjag** [comment]
I am doing few updates on the server. Please test it later.

**Comment by angied** [comment]
Fixed.
