### ISSUE TITLE
service agent/admin - Edit Enrollment

### ISSUE THREAD

**Issue by alamora** [NASA-Tournament-Lab/coeci-cms-mpsp#5]
Migrated from: https://apps.topcoder.com/bugs/browse/PESP-481

When you edit an enrollment from the Enrollment tab search, the Personal Info is there but the rest of the tabs are blank. The information the provider entered into the application should be there if the agent or admin edits to approve/deny. And if you click Re-submit Enrollment it goes through fine, but the information is all missing.

**Comment by cyberjag** [comment]
This is working as expected. Can you please test it again?

**Comment by angied** [comment]
Fixed.
