### ISSUE TITLE
Not checking OIG database

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#51]
I added a new physician record using the name, SSN, and DOB of a person known to be on the OIG list as an excluded provider, but under Review Application the EXCLUDED PROVIDER VERIFICATION IN OIG is checked, meaning name was not found in list.

**Comment by alamora** [comment]
We are looking into this.

**Comment by cyberjag** [comment]
Andy,

None of the configured urls in our application now works for OIG.

http://exclusions.oig.hhs.gov/search.aspx - REDIRECT happens, so HTML Parsing Fails
https://exclusions.oig.hhs.gov/Verification.aspx - Server Error  404
http://exclusions.oig.hhs.gov/ExclusionTypeCounts.aspx - Server Error 404

**Comment by alamora** [comment]
We definitely need to fix that.  Can you do it?

Sent on the go.

Jerrish Varghese notifications@github.com wrote:

Andy,

None of the configured urls in our application now works for OIG.

http://exclusions.oig.hhs.gov/search.aspx - REDIRECT happens, so HTML Parsing Fails
https://exclusions.oig.hhs.gov/Verification.aspx - Server Error 404
http://exclusions.oig.hhs.gov/ExclusionTypeCounts.aspx - Server Error 404

**Comment by cyberjag** [comment]
We have to do the HTML parsing again for this datasource from scratch. The entire DOM is changed for the website.

**Comment by alamora** [comment]
Ok.  Well lets do it.

Sent on the go.

Jerrish Varghese notifications@github.com wrote:

We have to do the HTML parsing again for this datasource from scratch. The entire DOM is changed for the website.

**Comment by alamora** [comment]
This is in progress via a bug race:
https://apps.topcoder.com/bugs/browse/BUGR-9324

**Comment by cyberjag** [comment]
This is fixed.

http://ec2-54-242-108-250.compute-1.amazonaws.com:9080/cms/agent/enrollment/screeningReview?id=11011

**Comment by alamora** [comment]
I see that the provider correctly was rejected because the exclusion list check failed.  But no details can be seen as the log wasn't created or couldnt be found:

http://ec2-54-242-108-250.compute-1.amazonaws.com:9080/cms/agent/enrollment/autoScreeningResult?type=LICENSE%20VERIFICATION&id=11011&licenseId=10011

Is that a  bug?

**Comment by cyberjag** [comment]
That link is for license verification. I think there is no external source for verifying the license number.

![image](https://f.cloud.github.com/assets/4492389/1815183/5742d810-6f10-11e3-94de-9d0c33d47298.png)

**Comment by alamora** [comment]
OK thanks - we should make that message more clear if possible.  Its
confusing right now (not a major issue though).

On Fri, Dec 27, 2013 at 11:03 AM, Jerrish Varghese <notifications@github.com

**Comment by angied** [comment]
It connects and returns the exclusion, but the SSN/EIN Matched is No.

![image](https://f.cloud.github.com/assets/4697941/1827319/e1ffd36e-722f-11e3-8b64-a02536b41932.png)

Can it return the same results the OIG site displays?

![image](https://f.cloud.github.com/assets/4697941/1827317/ce57c524-722f-11e3-9ebf-00550c818f4e.png)
