### ISSUE TITLE
Tab order and change - Personal Care Provider Organizations

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#55]
We need some of the information from PCPOs up front to assign them an agency ID, but other information will not be available from them until after the agency ID is assigned and they've attended training. 

Move the insurance and bonds section to a new Insurance tab (they won't have these until after training), and reorder tabs to:

Organization Info > Facility Credentials > Qualified Professional > Ownership Info > Insurance > Individual Members > Summary > Provider Statement.

The provider will only be able to complete the first four (through Ownership Info) and have to save as a draft. Add filler text to Ownership Info tab that will become instructions for the provider's next steps.

**Comment by alamora** [comment]
Is it possible to boil this down to a must-have-for-it-to-work list?  I dont think we'll be able to reorder tabs.

**Comment by angied** [comment]
Instead, let's change the insurance and bonds to not-required. We can add text instructions for the provider to come back and upload them after training.
