### ISSUE TITLE
Insurance and Bonds - Personal Care Provider Organization

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#56]
Change the insurance and bonds to not-required. We can add text instructions for the provider to come back and upload them after training.

**Comment by angied** [comment]
Still indicated as required. See screenshot.
![image](https://f.cloud.github.com/assets/4697941/1707210/4e6a1e70-60fa-11e3-8570-9078a5b345f2.png)

**Comment by cyberjag** [comment]
This is fixed and can be tested.

**Comment by angied** [comment]
Fixed.
