### ISSUE TITLE
Individual Member Info - Personal Care Provider Organization

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#58]
Need to add "BGS Study ID" and "BGS Clearance Date" fields to each individual member. "Start Date" cannot precede Clearance Date.

**Comment by cyberjag** [comment]
BGS Study ID and BGS Clearance Date - Are these fields <b>required</b> for PCPO Member affiliation?

**Comment by angied** [comment]
Yes.

**Comment by angied** [comment]
Fixed.
