### ISSUE TITLE
NPI Requirement - Home & Community Based Services (Waivered)

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#61]
NPI is currently a required field but HCBS providers do not need to have an NPI.

**Comment by alamora** [comment]
How about an UMPI?

Andy LaMora
TopCoder, Inc
(p) 917-312-7406

**Comment by angied** [comment]
If they are updating or re-enrolling, they could have an UMPI. Newly enrolling won't have an UMPI  yet.

**Comment by angied** [comment]
Fixed.

Just need to update the field label to NPI/UMPI. We don't require an NPI, but they can give us one if they have it.
