### ISSUE TITLE
Disclosing Entity Structure - Organization Providers

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#63]
If you select an Entity Type, expand the Individual Person Ownership or Control Interest, the Type (of individual) drop down list is specific to the Entity Type. But if you try to change the Entity Type, the individual Type drop down no longer functions. It does not update with the new list.

**Comment by cyberjag** [comment]
This seems to be working in my browser. If you still see this error can you please paste the screenshots here?

**Comment by angied** [comment]
Fixed.
