### ISSUE TITLE
EDI Trading Partner Type

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#70]
Add three additional options to top of Organization Info tab of newly enrolling EDI Trading Partner:

Medicare Carrier
Mental Health Information System Grantee
MN Health Insurance Exchange Carrier

**Comment by cyberjag** [comment]
https://apps.topcoder.com/bugs/browse/BUGR-9675

**Comment by angied** [comment]
fixed
