### ISSUE TITLE
Type of License - Private Duty Nurse

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#77]
Add the following to the Type of License drop down for Private Duty Nurse:

Licensed Practical Nurse
Class A License

If provider selects LPN display text "LPNs who are independent must also have a Class A license from the MN Dept of Health."

3.1.7 of Conceptualization Document - Medicaid Provider Screening Portal - Screening Rules Part 2.doc

**Comment by angied** [comment]
Partially fixed. 

If adding LPN license without the Class A, this error correctly posts upon submission:
![image](https://f.cloud.github.com/assets/4697941/1708522/c955fe50-610f-11e3-9e28-41f889d5735d.png)

However, the second line: "Registered Nurse license in state of practice is required" is incorrect. They can have either the RN license, OR the LPN + Class A license.

**Comment by cyberjag** [comment]
This is fixed and can be tested.

**Comment by angied** [comment]
Fixed.
