### ISSUE TITLE
Adding Individual Person Ownership - Organization Provider

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#79]
Similar to the issue reported in #40, adding an Individual Person Ownership on the Ownership Info tab of Organization Enrollment copies the information from the previously entered Individual.

If you have two Individuals entered, and you add a third, two are added; one is copied from the first, one is copied from the second. 

Additionally, there is no way to remove them.

**Comment by angied** [comment]
Tested, partially fixed. 

The new sections are blank, but clicking Add Another Individual adds as many sections as are already filled out. I added two owners, and clicked Add, and it added 2 new sections.

**Comment by alamora** [comment]
Angie - does having the two added sections actually prevent successfully completing the form?

**Comment by angied** [comment]
Fixed.
