### ISSUE TITLE
Nurse Practitioner

### ISSUE THREAD

**Issue by owgriffin** [NASA-Tournament-Lab/coeci-cms-mpsp#8]
Multiple Issues
- Only one specialty type is available for this provider type
- You are forced into selecting a mental health specialty type
- You are forced to enter a highest degree level
- Attempting to remove the specialty type does not remove the degree data
- You receive an error message saying that the specialty type does not require degree information

**Comment by angied** [comment]
These are the specialties that should be available:
Gerontological
Pediatric
Family
Adult
OB/GYN
Psychiatric/Mental Health
Neonatal
Women’s Health Care
Acute Care

Highest Degree Earned should only be required if Psychiatric/Mental Health is selected.

**Comment by angied** [comment]
Fixed.
