### ISSUE TITLE
Renew Enrollment - Provider

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#87]
The Provider Statement tab comes up populated with all the previously submitted information. Because the provider is reattesting, this tab should be blank so they have to select the disclosure answers, type their name, and type the date. 

When trying to submit, there's an error:

Please correct the following errors:
You must accept the Provider Agreement.

Unchecking and rechecking does not solve the error. Cannot submit renewal.

**Comment by angied** [comment]
There are no approved records under the test provider role I created, and I am unable to submit a new one to approve to test this issue. I cannot get past the licensing tab on any provider type because I get the generic Server Error.

**Comment by cyberjag** [comment]
I just submitted a new enrollment for Acupuncturist. Can you please tell me the provider type which is giving this Server Error?

**Comment by angied** [comment]
I attempted Dentist, Licensed Independent Clinical Social Worker, Licensed Psychologist, and Podiatrist.

**Comment by cyberjag** [comment]
I created 3 new enrollments for Dentist, LICSW, LP without any issues. For Podiatrist a rule update is required. Can you please log it as a separate ticket and close this one?

**Comment by angied** [comment]
I cleared my cache and again attempted to enroll License Psychologist, and I get the same error trying to move past the licensing screen.

**Comment by cyberjag** [comment]
There was a database space issue in VM which I fixed now. Can you please try again?

**Comment by angied** [comment]
Ok, I can continue with an enrollment so that issue is fixed. 

I just entered a new issue I encountered when trying to approve the submitted application so I can test the original issue in this thread. Need to get that resolved before I can test this.

**Comment by angied** [comment]
Original issue fixed.
