### ISSUE TITLE
Physician - State licensing board screening not executing

### ISSUE THREAD

**Issue by owgriffin** [NASA-Tournament-Lab/coeci-cms-mpsp#9]
Multiple physicians have been entered - the state licensing board screening lookup is not working

**Comment by alamora** [comment]
Was a valid license code used (format and/or actual value)?

**Comment by alamora** [comment]
Better yet, can you provide the log or log excerpt/stack trace?

**Comment by alamora** [comment]
Closing this ticket for now since the redeployment seems to have resolved this.  If the problem continues a new ticket should be issued.
