### ISSUE TITLE
Accepting Provider Agreement

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#90]
Enrollment for any provider type cannot be submitted due to the following error:

Please correct the following errors:

You must accept the Provider Agreement.

All agreements have been checked. Unchecking and rechecking does not fix.

**Comment by cyberjag** [comment]
The agreement name is used in the validation rules and currently the name used is Provider Agreement. I noticed that it is changed to MHCP Provider Agreement in the sever. If that is required I can update the rules for this. Currently for the demo to work I changed the agreement name to Provider Agreement so that you can submit enrollment can work.

**Comment by angied** [comment]
Is it possible to not have the agreement name itself written into the rules? Provider requirements change often, and we have to add or remove agreements, addendums, or assurance statements. If the specific name is written into the rules, then Service Admin won't be able to update the Provider Type business rules with any changes.

**Comment by cyberjag** [comment]
I think it will be possible to remove the name from the rules and use the agreement id. In that case you won't be able to delete an agreement.

**Comment by cyberjag** [comment]
Ideally speaking if the name of the agreement changes that means its a business rule change also. So the rule also needs an update whenever there is a change in the name of the agreement.

**Comment by angied** [comment]
Assuming a Service Admin can make the business rule update by editing the Provider Type business rules in the Function tab, that will be fine.

**Comment by alamora** [comment]
cyberjag, I dont see this ticket assigned to our contest list.  Should it be resolved?

**Comment by cyberjag** [comment]
The root issue is fixed, however Angie's assumption is partially correct. You can edit business rules for a provider type not via Service Admin login but using Guvnor.

**Comment by cyberjag** [comment]
This should be working as expected now.

**Comment by angied** [comment]
Fixed.

**Comment by alamora** [comment]
Sweet.
