### ISSUE TITLE
NPI Required - Day Training & Habilitation

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#96]
NPI should not be required for Day Training & Habilitation providers.

**Comment by angied** [comment]
Still displaying as required in the amazon environment.

**Comment by alamora** [comment]
Jerrish FYI I do not see a fix for #96 checked in, according to the history log.

**Comment by cyberjag** [comment]
Will commit the change. I missed the jsp.

**Comment by cyberjag** [comment]
This is fixed and can be tested.

**Comment by angied** [comment]
Fixed.
