### ISSUE TITLE
County Fields - All provider types

### ISSUE THREAD

**Issue by angied** [NASA-Tournament-Lab/coeci-cms-mpsp#98]
The County Fields across all provider types on various tabs are still just 3 characters. The field should either be a drop down, or auto-complete as the provider types it in.

**Comment by cyberjag** [comment]
This fix is missed in today's deployment. Please test it tomorrow.

**Comment by angied** [comment]
The County field is longer but it appears to be inactive. I cannot type anything into it.

Also, we can remove the County field from the Reimbursement Address section of all provider types. We only need to collect the county for the primary practice.
![image](https://f.cloud.github.com/assets/4697941/1714542/1a6b9306-61a4-11e3-9901-af9884c13d62.png)

**Comment by cyberjag** [comment]
This is ready to be tested.

**Comment by angied** [comment]
Fixed.
